### PR TITLE
closes #32 - updated the link to the CONTRIBUTE

### LINKED ISSUE #32: CONTRIBUTING link is broken
https://github.com/18F/dev-environment/blame/18f-pages/README.md#L52
The `CONTRIBUTING` link is broken and returns a 404

### PR DESCRIPTION
**Pull request by johnscancella**
Pull request to close #32

### CODE REVIEW

**Comment by mbland** [comment]
Actually, I think the correct thing to do here is to add the CONTRIBUTING file to the repo. :stuck_out_tongue:  Can you actually revert this commit and add a copy of the very file you're linking to there?

Also @brittag may have some thoughts, as she's taken the mantle of improving our repo documentation.

**Comment by johnscancella** [comment]
Sure if that is what you want. I just know from experience it is easier to update documentation when it isn't copied N times all over the place. I should have an updated pull request later for you

**Comment by johnscancella** [comment]
@mbland updated pull request

**Comment by ccostino** [comment]
Thank you, @johnscancella!

**Pull request merged**
