### PR TITLE
first cut at CI page

### PR DESCRIPTION
**Pull request by johnscancella**

### CODE REVIEW

**Comment by johnscancella** [comment]
CC @emileighoutlaw Want to work your word smithing magic?

**Comment by emileighoutlaw** [comment]
This looks great @johnscancella ! I made some edit suggestions, but they're all very minor!

**Comment by johnscancella** [comment]
I _think_ I got all of your edits, but let me know if I missed any and I will add them as well.

**Comment by emileighoutlaw** [comment]
Looks great!

**Pull request merged**
