### PR TITLE
Style style edits

### PR DESCRIPTION
**Pull request by emileighoutlaw**
Very small edits.

### CODE REVIEW

**Comment by mbland** [comment]
cc: @johnscancella

**Comment by johnscancella** [comment]
@emileighoutlaw thanks for fixing my poor grammer - my wife tells me I am not allowed to talk to our child for fear he will pick it up ;)

**Comment by emileighoutlaw** [comment]
Of course! :) Grammar I understand. Javascript on the other hand . . .

**Comment by johnscancella** [comment]
I with you there, give me a strongly typed language any day

**Pull request merged**
