### PR TITLE
Update to use guides_style_18f, Jekyll 3

### PR DESCRIPTION
**Pull request by mbland**
Note that most of the changes are for guides_style_18f; the only Jekyll 3 upgrade change is to add `incremental: true` to the configuration.

cc: @emileighoutlaw @johnscancella @acdha

### CODE REVIEW

**Comment by johnscancella** [comment]
Just curious, did you mean to delete `assets/img/18f-logo.png`?
otherwise looks good to me.

**Comment by mbland** [comment]
@johnscancella Yeah, because it comes from the `guides_style_18f` gem now. That gem's designed to make it easy to import all the Jekyll boilerplate (hence all the deletions), and the 18F logo is part of that. (Also working on porting it to use the U.S. Web Design Standards.)

**Comment by johnscancella** [comment]
Cool! To be honest I never really understood all the style stuff. So, not really knowing, is there anyway to test this? Like maybe some image difference software?

**Comment by mbland** [comment]
I just run `./go serve` and click through a few things. :-P It would be useful to have a test to ensure all the sidebar behavior works, as that's the trickiest part. Could probably get some WebDriver/Selenium tests around that at some point (and that point is coming soon, I think).

**Comment by mbland** [comment]
OK, since this is just a style/Jekyll update, going to go ahead and merge.

**Pull request merged**
